name: 'tg_dbt'
version: '1.0.0'
config-version: 2
profile: 'tg_dbt'

model-paths: ["models"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  tg_dbt:
    staging:
      materialized: view
    marts:
      materialized: table
      +schema: marts