version: '3.8'

services:
  app:
    build: .
    container_name: data_pipeline_app
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./data:/app/data
      - ./dbt:/app/dbt
      - ./src:/app/src
      - ~/.dbt:/root/.dbt
    command: ["tail", "-f", "/dev/null"]

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: